# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: write_service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'write_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13write_service.proto\x12\x05write\".\n\x0cWriteRequest\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\x12\x10\n\x08priority\x18\x02 \x01(\x08\"\x1f\n\rWriteResponse\x12\x0e\n\x06status\x18\x01 \x01(\t2F\n\x0cWriteService\x12\x36\n\tWriteData\x12\x13.write.WriteRequest\x1a\x14.write.WriteResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'write_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_WRITEREQUEST']._serialized_start=30
  _globals['_WRITEREQUEST']._serialized_end=76
  _globals['_WRITERESPONSE']._serialized_start=78
  _globals['_WRITERESPONSE']._serialized_end=109
  _globals['_WRITESERVICE']._serialized_start=111
  _globals['_WRITESERVICE']._serialized_end=181
# @@protoc_insertion_point(module_scope)
