# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import write_service_pb2 as write__service__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in write_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class WriteServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateEvent = channel.unary_unary(
                '/WriteService/CreateEvent',
                request_serializer=write__service__pb2.CreateEventRequest.SerializeToString,
                response_deserializer=write__service__pb2.CreateEntityResponse.FromString,
                _registered_method=True)
        self.CreateUser = channel.unary_unary(
                '/WriteService/CreateUser',
                request_serializer=write__service__pb2.CreateUserRequest.SerializeToString,
                response_deserializer=write__service__pb2.CreateEntityResponse.FromString,
                _registered_method=True)
        self.CreateDj = channel.unary_unary(
                '/WriteService/CreateDj',
                request_serializer=write__service__pb2.CreateDJRequest.SerializeToString,
                response_deserializer=write__service__pb2.CreateEntityResponse.FromString,
                _registered_method=True)
        self.CreateVenue = channel.unary_unary(
                '/WriteService/CreateVenue',
                request_serializer=write__service__pb2.CreateVenueRequest.SerializeToString,
                response_deserializer=write__service__pb2.CreateEntityResponse.FromString,
                _registered_method=True)
        self.CreateOrganizer = channel.unary_unary(
                '/WriteService/CreateOrganizer',
                request_serializer=write__service__pb2.CreateOrganizerRequest.SerializeToString,
                response_deserializer=write__service__pb2.CreateEntityResponse.FromString,
                _registered_method=True)
        self.PublishEvent = channel.unary_unary(
                '/WriteService/PublishEvent',
                request_serializer=write__service__pb2.CreatePublishRequest.SerializeToString,
                response_deserializer=write__service__pb2.CreateEntityResponse.FromString,
                _registered_method=True)


class WriteServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateEvent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateDj(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateVenue(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateOrganizer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PublishEvent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WriteServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateEvent': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateEvent,
                    request_deserializer=write__service__pb2.CreateEventRequest.FromString,
                    response_serializer=write__service__pb2.CreateEntityResponse.SerializeToString,
            ),
            'CreateUser': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateUser,
                    request_deserializer=write__service__pb2.CreateUserRequest.FromString,
                    response_serializer=write__service__pb2.CreateEntityResponse.SerializeToString,
            ),
            'CreateDj': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateDj,
                    request_deserializer=write__service__pb2.CreateDJRequest.FromString,
                    response_serializer=write__service__pb2.CreateEntityResponse.SerializeToString,
            ),
            'CreateVenue': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateVenue,
                    request_deserializer=write__service__pb2.CreateVenueRequest.FromString,
                    response_serializer=write__service__pb2.CreateEntityResponse.SerializeToString,
            ),
            'CreateOrganizer': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateOrganizer,
                    request_deserializer=write__service__pb2.CreateOrganizerRequest.FromString,
                    response_serializer=write__service__pb2.CreateEntityResponse.SerializeToString,
            ),
            'PublishEvent': grpc.unary_unary_rpc_method_handler(
                    servicer.PublishEvent,
                    request_deserializer=write__service__pb2.CreatePublishRequest.FromString,
                    response_serializer=write__service__pb2.CreateEntityResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'WriteService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('WriteService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class WriteService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/WriteService/CreateEvent',
            write__service__pb2.CreateEventRequest.SerializeToString,
            write__service__pb2.CreateEntityResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/WriteService/CreateUser',
            write__service__pb2.CreateUserRequest.SerializeToString,
            write__service__pb2.CreateEntityResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateDj(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/WriteService/CreateDj',
            write__service__pb2.CreateDJRequest.SerializeToString,
            write__service__pb2.CreateEntityResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateVenue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/WriteService/CreateVenue',
            write__service__pb2.CreateVenueRequest.SerializeToString,
            write__service__pb2.CreateEntityResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateOrganizer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/WriteService/CreateOrganizer',
            write__service__pb2.CreateOrganizerRequest.SerializeToString,
            write__service__pb2.CreateEntityResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PublishEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/WriteService/PublishEvent',
            write__service__pb2.CreatePublishRequest.SerializeToString,
            write__service__pb2.CreateEntityResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
